version: "3"

services:

  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: souvip
    ports:
      - "5432:5432"
    networks:
      souvip:

networks:
  souvip:
    driver: bridge